os:
- linux
- osx
- windows
language: node_js
node_js: node
cache:
  directories:
  - $HOME/.cache/yarn
  - node_modules
sudo: false
matrix:
  fast_finish: true
script:
- yarn test
notifications:
  email: false
