os:
- linux
- osx
- windows
language: node_js
node_js: node
cache:
  directories:
  - $HOME/.cache/yarn
  - node_modules
sudo: false
matrix:
  fast_finish: true
script:
- yarn test
after_success:
- travis_retry yarn global add codeclimate-test-reporter
- codeclimate-test-reporter < test/coverage/lcov.info
addons:
  code_climate:
    repo_token: 35d4a031138148b32b68c6f69866d2ecbe6cfffaed67347a90ca7b7bf6dc8415
notifications:
  email: false
